<?xml version="1.0"?>
<?HTMLTemplate version="0.1"?>
<!--================================================================================-->
<!--  This file was generated by IBM's HTMLToXSL Generator.                         -->
<!--================================================================================-->
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <?HTMLTemplate version="0.1"?>
  

  <!--================================================================================-->
  <!--  printoutGoing                                                                 -->
  <!--================================================================================-->
  <xsl:template name="printoutGoing">
    <html>
      <head>
        <meta content="text/html; charset=ISO-8859-1" http-equiv="Content-Type"/>
      </head>
      <body>
      <FONT align = "right" size="1" face="Arial Greek" color="#8000ff"> Estate software is developed by TeBS Labs, Bangalore. http://www.totalebizsolutions.com</FONT>
      <BR/>
        <xsl:call-template name="handleFirmDetails"/>
        <br/>
        <center>
          <table border="0" cellpadding="0" cellspacing="0">
            <tbody>
              <xsl:call-template name="handlerowData"/>
            </tbody>
          </table>
          <br/>
          <table border="1" cellpadding="0" cellspacing="0" width="60%">
            <tbody>
              <tr align="center" bgcolor="#8080ff">
                <th>Planks</th>
                <th>Runners</th>
                <th>Battons</th>
                <th>SLR</th>
                <th>Lapha</th>
                <th bgcolor="#c0c0c0">Total</th>
              </tr>
              <xsl:call-template name="handlesizeTotal"/>
            </tbody>
          </table>
        </center>
      </body>
    </html>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printFirmDetails                                                              -->
  <!--================================================================================-->
  <xsl:template name="printFirmDetails">
    <xsl:param name="firmAddress"/>
    <xsl:param name="firmName"/>
    <xsl:param name="billNo"/>
    <xsl:param name="orderNo"/>
    <xsl:param name="articles"/>
    <xsl:param name="lorryName"/>
    <xsl:param name="date"/>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
      <tbody>
        <tr>
          <td valign="top">
            To:
            <br/>Firm: <b>
            <xsl:value-of select="$firmName"/>
            </b><br/>Address: 
            <xsl:value-of select="$firmAddress"/>
          </td>
          <td>
            No: <xsl:value-of select="$billNo"/>
            <br/>
            Order No: <xsl:value-of select="$orderNo"/>
            <br/>
            Articles: <xsl:value-of select="$articles"/>
            <br/>
            Lorry No: <xsl:value-of select="$lorryName"/>
            <br/>
            Date: <xsl:value-of select="$date"/>
          </td>
        </tr>
      </tbody>
    </table>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printrowData                                                                  -->
  <!--================================================================================-->
  <xsl:template name="printrowData">
    <tr valign="top">
      <xsl:call-template name="handlesizeData"/>
    </tr>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printsizeData                                                                 -->
  <!--================================================================================-->
  <xsl:template name="printsizeData">
    <td>
      <table border="1">
        <tbody>
          <tr bgcolor="#ffff00">
            <th colspan="3">Dimension</th>
            <th rowspan="2">Pieces</th>
            <th rowspan="2">RFT</th>
            <th rowspan="2">CFT</th>
          </tr>
          <tr bgcolor="#ffff00">
            <th>L</th>
            <th>W</th>
            <th>T</th>
          </tr>
          <xsl:call-template name="handleload"/>
          <xsl:call-template name="handleloadTotal"/>
        </tbody>
      </table>
    </td>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printload                                                                     -->
  <!--================================================================================-->
  <xsl:template name="printload">
    <xsl:param name="cft"/>
    <xsl:param name="rft"/>
    <xsl:param name="qnt"/>
    <xsl:param name="thinkness"/>
    <xsl:param name="width"/>
    <xsl:param name="length"/>
    <tr>
      <td>
        <xsl:value-of select="$length"/>
      </td>
      <td>
        <xsl:value-of select="$width"/>
      </td>
      <td>
        <xsl:value-of select="$thinkness"/>
      </td>
      <td>
        <xsl:value-of select="$qnt"/>
      </td>
      <td>
        <xsl:value-of select="$rft"/>
      </td>
      <td>
        <xsl:value-of select="$cft"/>
      </td>
    </tr>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printloadTotal                                                                -->
  <!--================================================================================-->
  <xsl:template name="printloadTotal">
    <xsl:param name="cft"/>
    <xsl:param name="rft"/>
    <xsl:param name="qnt"/>
    <tr bgcolor="#c0c0c0">
      <th colspan="3">Total</th>
      <td>
        <xsl:value-of select="$qnt"/>
      </td>
      <td>
        <xsl:value-of select="$rft"/>
      </td>
      <td>
        <xsl:value-of select="$cft"/>
      </td>
    </tr>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printsizeTotal                                                                -->
  <!--================================================================================-->
  <xsl:template name="printsizeTotal">
    <xsl:param name="totalCFT"/>
    <xsl:param name="Lapha"/>
    <xsl:param name="SLR"/>
    <xsl:param name="Battons"/>
    <xsl:param name="Runners"/>
    <xsl:param name="planks"/>
    <tr align="center">
      <td>
        <xsl:value-of select="$planks"/>
      </td>
      <td>
        <xsl:value-of select="$Runners"/>
      </td>
      <td>
        <xsl:value-of select="$Battons"/>
      </td>
      <td>
        <xsl:value-of select="$SLR"/>
      </td>
      <td>
        <xsl:value-of select="$Lapha"/>
      </td>
      <td>
        <xsl:value-of select="$totalCFT"/>
      </td>
    </tr>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  Overide these methods to specify parameters and control flow logic            -->
  <!--================================================================================-->
  
<xsl:template name="handleFirmDetails">
    <xsl:call-template name="printFirmDetails"/>
  </xsl:template>
  
 

  <xsl:template name="handlerowData">
    <xsl:call-template name="printrowData"/>
  </xsl:template>
  

  <xsl:template name="handlesizeData">
    <xsl:call-template name="printsizeData"/>
  </xsl:template>
  

  <xsl:template name="handleload">
    <xsl:call-template name="printload"/>
  </xsl:template>
  

  <xsl:template name="handleloadTotal">
    <xsl:call-template name="printloadTotal"/>
  </xsl:template>
  

  <xsl:template name="handlesizeTotal">
    <xsl:call-template name="printsizeTotal"/>
  </xsl:template>
</xsl:transform>
