<?xml version="1.0"?>
<?HTMLTemplate version="0.1"?>
<!--================================================================================-->
<!--  This file was generated by IBM's HTMLToXSL Generator.                         -->
<!--================================================================================-->
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <?HTMLTemplate version="0.1"?>
  

  <!--================================================================================-->
  <!--  printfirm                                                                     -->
  <!--================================================================================-->
  <xsl:template name="printfirm">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta content="text/html; charset=ISO-8859-1" http-equiv="Content-Type"/>
        <meta content="IBM WebSphere Studio" name="GENERATOR"/>
        <title>Firm Table</title>
      </head>
      <body>
        <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tbody>
        <tr>
        <xsl:call-template name="handledetails"/>
        <td>
	            <img align="right" border="0" height="90" src="../../../images/logo.gif" width="140"/>
          </td>
        </tr>
	      </tbody>
    </table>
        <br />
        <center>
          <table border="1" cellpadding="0" cellspacing="0">
            <tbody>
              <tr align="center" bgcolor="#ffff00">
                <th>SNo</th>
                <th>Order No</th>
                <th>Load No</th>
                <th>Date</th>
                <th>Runners</th>
                <th>Planks</th>
                <th>Battons</th>
                <th>SLR</th>
                <th>Lapha</th>
                <th>Others</th>
                <th>TotalCFT</th>
                <th>Amount</th>
              </tr>
              <xsl:call-template name="handleload"/>
            </tbody>
          </table>
        </center>
      </body>
    </html>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printdetails                                                                  -->
  <!--================================================================================-->
  <xsl:template name="printdetails">
    <xsl:param name="firmAddress"/>
    <xsl:param name="firmName"/>
  
          <td valign="top">Firm: 
            <b><xsl:value-of select="$firmName"/></b>
            <br />
            Address: 
            <xsl:value-of select="$firmAddress"/>
          </td>
          
        
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printload                                                                     -->
  <!--================================================================================-->
  <xsl:template name="printload">
    <xsl:param name="amount"/>
    <xsl:param name="totalCFT"/>
    <xsl:param name="others"/>
    <xsl:param name="lapha"/>
    <xsl:param name="SLR"/>
    <xsl:param name="battons"/>
    <xsl:param name="planks"/>
    <xsl:param name="runners"/>
    <xsl:param name="date"/>
    <xsl:param name="loadName"/>
    <xsl:param name="orderNo"/>
    <xsl:param name="sno"/>
    <tr align="center">
      <td>
        <xsl:value-of select="$sno"/>
      </td>
      <td>
        <xsl:value-of select="$orderNo"/>
      </td>
      <td>
        <xsl:value-of select="$loadName"/>
      </td>
      <td>
        <xsl:value-of select="$date"/>
      </td>
      <td>
        <xsl:value-of select="$runners"/>
      </td>
      <td>
        <xsl:value-of select="$planks"/>
      </td>
      <td>
        <xsl:value-of select="$battons"/>
      </td>
      <td>
        <xsl:value-of select="$SLR"/>
      </td>
      <td>
        <xsl:value-of select="$lapha"/>
      </td>
      <td>
        <xsl:value-of select="$others"/>
      </td>
      <td>
        <xsl:value-of select="$totalCFT"/>
      </td>
      <td>
        <xsl:value-of select="$amount"/>
      </td>
    </tr>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  Overide these methods to specify parameters and control flow logic            -->
  <!--================================================================================-->
  

  <xsl:template name="handledetails">
    <xsl:call-template name="printdetails"/>
  </xsl:template>
  

  <xsl:template name="handleload">
    <xsl:call-template name="printload"/>
  </xsl:template>
</xsl:transform>
