<?xml version="1.0"?>
<?HTMLTemplate version="0.1"?>
<!--================================================================================-->
<!--  This file was generated by IBM's HTMLToXSL Generator.                         -->
<!--================================================================================-->
<xsl:transform version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<?HTMLTemplate version="0.1"?>

  <!--================================================================================-->
  <!--  printfirm                                                                     -->
  <!--================================================================================-->
  <xsl:template name="printfirm">
    <html>
      <head>
        <meta content="text/html; charset=ISO-8859-1" http-equiv="Content-Type"/>
        
        <link rel="stylesheet" type="text/css" href="../../../jars/config/mystyle.css"/>
        
      </head>
      <body>
      
        <table border="0" cellpadding="0" cellspacing="0">
        <tbody>
        <tr>
         <td>
          <xsl:call-template name="handledetails"/>
         </td>
        </tr>
        </tbody>
        </table>
        
        <br />
          <table class="firm" border="1" cellpadding="0" cellspacing="0">
            <thead>
              <tr bgcolor="#ffff00">
                <th>SNo</th>
                <th>Order No</th>
                <th>Load No</th>
                <th>Load Date</th>
                <th>Runners</th>
                <th>Planks</th>
                <th>Battons</th>
                <th>SLR</th>
                <th>Lapha</th>
                <th>Others</th>
                <th>TotalCFT</th>
                <th>Amount</th>
              </tr>
              </thead>
              <tbody>
              <xsl:call-template name="handleload"/>
              </tbody>
          </table>
        
      </body>
    </html>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printdetails                                                                  -->
  <!--================================================================================-->
<xsl:template name="printdetails">
    <xsl:param name="firmAddress"/>
    <xsl:param name="firmName"/>
    
    <table class="others" border="0" cellpadding="0" cellspacing="0">
       <tbody>
       <tr>
          <td><b>Firm Name</b> </td>
          <td>&#160;&#160;<xsl:value-of select="$firmName"/></td>
       </tr>
       <tr>
            <td><b>Address</b></td>
            <td>&#160;<xsl:value-of select="$firmAddress"/></td>
       </tr>
       <tr>
	    <td/>
	    <td><hr/>
            <b>Number of Loads =</b>&#160;&#160;&#160;&#160;&#160;&#160;&#160;and &#160;<b>Total CFT =</b>&#160;
	    </td>
        </tr>
       </tbody>
    </table>
  </xsl:template>
  

  <!--================================================================================-->
  <!--  printload                                                                     -->
  <!--================================================================================-->
  <xsl:template name="printload">
    <xsl:param name="amount"/>
    <xsl:param name="totalCFT"/>
    <xsl:param name="others"/>
    <xsl:param name="lapha"/>
    <xsl:param name="SLR"/>
    <xsl:param name="battons"/>
    <xsl:param name="planks"/>
    <xsl:param name="runners"/>
    <xsl:param name="date"/>
    <xsl:param name="loadName"/>
    <xsl:param name="orderNo"/>
    <xsl:param name="sno"/>
    <tr align="center">
      <td>
        <xsl:value-of select="$sno"/>
      </td>
      <td>
        <xsl:value-of select="$orderNo"/>
      </td>
      <td>
        <xsl:value-of select="$loadName"/>
      </td>
      <td>
        <xsl:value-of select="$date"/>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$runners"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$planks"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$battons"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$SLR"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$lapha"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$others"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$totalCFT"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
      <td>
        <xsl:call-template name="printVar">
		   <xsl:with-param name="var">
		      <xsl:value-of select="$amount"/>
	           </xsl:with-param>
        </xsl:call-template>
      </td>
    </tr>
  </xsl:template>
  
  <!--================================================================================-->
  <!--  Formats & prints the decimal into xx.yy string                              -->
  <!--================================================================================-->
  
<xsl:template name="printVar">
    <xsl:param name="var" select="0.0"/>
    <xsl:if test="$var != ''">
    <xsl:if test="$var != 0.0">
      <xsl:variable name="deci" select="substring-after($var,'.')" />
      <xsl:variable name="int" select="substring-before($var,'.')" />
        <xsl:value-of select="concat($int, '.', substring($deci,1,2))"/>      
    </xsl:if>
    </xsl:if>
</xsl:template>

  <!--================================================================================-->
  <!--  Overide these methods to specify parameters and control flow logic            -->
  <!--================================================================================-->
  

  <xsl:template name="handledetails">
    <xsl:call-template name="printdetails"/>
  </xsl:template>
  

  <xsl:template name="handleload">
    <xsl:call-template name="printload"/>
  </xsl:template>
</xsl:transform>
